### PR TITLE
Integrate a --refactor option

### PR DESCRIPTION
**Pull request by mpickering**
Is this like what you had in mind? 

Using a temporary file rather than dealing with stdin later means that you can use a filter in vim to process the file to apply refactorings. This plays much nicer in my brief experience writing vimscript but I'm not sure it's a good idea.

### CODE REVIEW

**Comment by mpickering** [comment]
Ah, I see now the non-zero exit's are when there are suggestions to apply.

**Comment by ndmitchell** [comment]
I don't understand why you are writing stdin to a temp file. How can vim work with a temp file you delete before giving back to them?

**Comment by mpickering** [comment]
I arranged it like this because I found it nicer in vim to work with filters which send the current buffer to stdin and  replace it with what comes back on stdout. I wrote stdin to a temp file so that apply-refact could inspect what was on stdin (and the behaviour is uniform whether the input came from a file or stdin). This way apply-refact reads the temp file and produces output on stdout (which vim picks up) before hlint cleans up the temporary file.

**Comment by ndmitchell** [comment]
Ok, now I understand. I think I'd push that file creation down to just the refact path since temp files are always possibly less robust. Can you also use the temp file operations from the extra library since that's already an hlint dependency. With that, it looks good.

**Comment by mpickering** [comment]
I just pushed the suggested changes. If you want to try it out then building hlint from this patch and apply-refact from [here](https://github.com/mpickering/apply-refact) should work well together.

**Comment by ndmitchell** [comment]
Thanks, all looks good - I've merged.

**Pull request merged**
