### PR TITLE
Don't suggest a fix in "Use DerivingStrategies"

### PR DESCRIPTION
**Pull request by divarvel**
When no deriving strategies on newtypes are not explictly set, it's not possible to know the actual behaviour picked by GHC, so we can't suggest a semantics-preserving replacement.

Following discussion on https://github.com/ndmitchell/hlint/issues/690

### CODE REVIEW

**Comment by ndmitchell** [comment]
CI is failing because of an HLint violation: https://travis-ci.org/ndmitchell/hlint/jobs/552901146

**Comment by ndmitchell** [comment]
Otherwise looks great

**Comment by ndmitchell** [comment]
Thanks! I needed to change the tests to assert they no longer produced anything, which I've done.

**Comment by divarvel** [comment]
Oh sorry, I forgot that part. Thanks!

Le lun. 1 juil. 2019 à 22:06, Neil Mitchell <notifications@github.com> a
écrit :

**Pull request merged**
