### PR TITLE
compare `on` a -> comparing a

### PR DESCRIPTION
**Pull request by siraben**
``compare `on` a ``-> `comparing a `

### CODE REVIEW

**Comment by siraben** [comment]
Hm, can't seem to make the CI happy.

**Comment by siraben** [comment]
Can't seem to make the CI happy with a test case involving two different rewrites: ` last (sortBy (compare `on` fst) xs)`.

**Comment by ndmitchell** [comment]
Thanks for the patch. This used to be a hint (introduced in f0b076ba0f4f4f8c979416e9e8dca924b21dd279), but got removed in d9440e29b961f607168c09206bec3cd449873cb6 because it turned out to be a hint that a reasonable number of people disabled. The problem is that `comparing` is very much a special case, whereas learning the `on` function has a lot more value to it.

**Comment by siraben** [comment]
Aw, I see. Thanks!

**Pull request closed without merging**
