### PR TITLE
Use Numerical Value For Nonroot User To Avoid Additional Layer

### PR DESCRIPTION
**Pull request by brandshaide**
Avoid user  (`app`) creation as it's creating a unnecessary additional layer and the user itself is not being used anyway. Instead prefer to use numerical values, i. e. as this PR is introducing with a `uid` of `1000` for a `nonroot` user.

### CODE REVIEW

**Comment by ndmitchell** [comment]
CC @pbrisbin for a view on this. I have no real idea, but happy to push the merge button if those who contributed think its some good idea.

**Comment by pbrisbin** [comment]
I get where you're coming from, and it's a good idea layer-wise, but the SPEC actually says specifcally an `app` user with id `9000`:

> Engines are always run as a user `app` with UID and GID of 9000, and never `root`.

https://github.com/codeclimate/spec/blob/master/SPEC.md#security-restrictions

I don't know how much they enforce this, and having any non-root user should satisfy the actual security concerns (I think?), but technically this would make the image violate the spec as it's currently written. So I'm a soft-no, myself.

**Comment by brandshaide** [comment]
thank, @pbrisbin for diggin into this. Of course we want to comply to the specs and thus leave it like it is. 

>  [...]don't know how much they enforce this, and having any non-root user should satisfy the actual security concerns (I think?) [...]
me neither - and AFAIK it doesn't make as user "more secure" by giving him a `UID` way larger than 1000. 

> Engines are always run as a user app with UID and GID of 9000, and never root.
Hm, but the `Dockerfile` does not contain creation of a correspondig `GID`...

**Comment by ndmitchell** [comment]
If the decision is to leave it as it is, but for slightly subtle reasons, maybe a comment in the Docker file would be useful?

**Comment by pbrisbin** [comment]
> Hm, but the Dockerfile does not contain creation of a correspondig GID...

:man_shrugging: 

> maybe a comment in the Docker file would be useful?

A comment at the top linking to the SPEC sounds pretty reasonable. There are a few things a `Dockerfile` is supposed to do, so that might be better then a comment specifically near or about the `app` user?

**Comment by ndmitchell** [comment]
Happy with whatever comments you think are best.

**Comment by brandshaide** [comment]
I'll leave a comment on top of the  `Dockerfile` as suggested by @pbrisbin .

**Comment by brandshaide** [comment]
> maybe a comment in the Docker file would be useful? 

done :-)

**Comment by pbrisbin** [comment]
Works for me!

**Comment by ndmitchell** [comment]
Thanks!

**Pull request merged**
