### PR TITLE
Adds eta-reduction for function match with a where clause

### PR DESCRIPTION
**Pull request by SarthakKumar1997**
Previously, if I uncommented the commented code, and wrote a function like this:

```haskell
fastFib n = fib' 0 1 n
  where
    fib' a _ 0 = a
    fib' a b n = fib' b (a + b) (n - 1)
```

Eta-reduction would be detected but not work.

This has now been rectified, using a `chooseLoc` function. It would be changed to:

```haskell
fastFib = fib' 0 1
  where
    fib' a _ 0 = a
    fib' a b n = fib' b (a + b) (n - 1)
```

### CODE REVIEW

**Comment by ndmitchell** [comment]
There are a bunch of test failures - see https://travis-ci.org/ndmitchell/hlint/jobs/550291288 for example. Can you take a look through them and fix them (perhaps by adjusting the tests). Seems reasonable though.

**Comment by ndmitchell** [comment]
CC @zliu41 - this seems like a refactoring fix. Is this one we've already got covered?

**Comment by zliu41** [comment]
@ndmitchell Yeah, this has been fixed.

This PR works by expanding the srcspan of the hint to include the `where` block, which would be undesirable if the `where` block is big. It could have been improved by only expanding the srcspan of `ideaRefactoring`, but since apply-refact cannot apply refactorings with overlapping srcspans, it means if there's another hint within the `where` block, it can only be applied by running apply-refact twice. I made a fix in apply-refact which obviates the need to expand any srcspan from HLint.

**Comment by ndmitchell** [comment]
Thanks!

**Pull request closed without merging**
