### PR TITLE
Add warnings for redundant flip

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by josephcsible** [comment]
I was on the fence about suggesting `g >>= flip f` instead be changed to `g <**> f` to keep things in order, but `<**>` requires `import Control.Applicative`. Do you think it's worth doing anyway?

**Comment by ndmitchell** [comment]
I think keeping the terms in order would be better if we can, so I think suggesting `<**>` with a Control.Applicative import is the right thing to do. Everything else looks very nice, so will merge with that update.

**Comment by josephcsible** [comment]
Done.

**Comment by ndmitchell** [comment]
Thanks!

**Pull request merged**
