### PR TITLE
Lambda refactor

### PR DESCRIPTION
**Pull request by ndmitchell**
Thanks for the pull request!

By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.

If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.

### CODE REVIEW

**Comment by ndmitchell** [comment]
CC @googleson78 - the stuff in this branch is too good, so hijacking it :-)

**Comment by ndmitchell** [comment]
Fixes all the tests, so can't help but merge it!!!

**Comment by googleson78** [comment]
Thanks! I was trying to fix up the other tests that I disabled before submitting this, but I guess there's no issue with doing that later.

**Comment by ndmitchell** [comment]
Yep, happy to take a subsequent patch for that.

**Pull request merged**
