### PR TITLE
Suggest uncurry f (a, b) ==> f a b.

### LINKED ISSUE #1218: New suggestion request for: `f . uncurry (zipWith g) $ (a, b)`
This looks like a good one to have in general:

```haskell
module Z where
lhs f g a b = f . uncurry (zipWith g) $ (a, b)
rhs f g a b = f $ zipWith g a b
```
even GHC think they are the same on -O2:
```sh
$ ghc -O2 Z.hs -ddump-simpl
[1 of 1] Compiling Z                ( Z.hs, Z.o )

==================== Tidy Core ====================
<omitted>
rhs [InlPrag=NOUSERINLINE[2]]
  :: forall c t a b. ([c] -> t) -> (a -> b -> c) -> [a] -> [b] -> t
<omitted>
rhs = lhs
<omitted>
```

### PR DESCRIPTION
**Pull request by Javran**
Closes #1218.

(template content removed, no licensing concern from my side.)

### CODE REVIEW

**Comment by Javran** [comment]
Side note: while writing tests for this change, I noticed that if I write:
```
# issue1218 = f . uncurry (zipWith g) $ (a, b) -- f $ zipWith g a b
```
It fails the test with following message:

```
Found:
  f . uncurry (zipWith g) $ (a, b)
Perhaps:
  zipWith g (zipWith g a b)

WANTED: f $ zipWith g a b



Tests failed (1 of 790)
```

which looks wrong, not sure if I'm writing tests correctly.

**Comment by ndmitchell** [comment]
Thanks for the diff - sorry it's taken a while to look at. Generally I recommend people don't update the changelog, and then I do it after the patch lands - otherwise conflicts are somewhat inevitable (as has happened here).

So the issue is:

```
TEST FAILURE (BAD REFACTORING)
SRC: /home/runner/.cabal/store/ghc-8.10.3/hlint-3.2.7-a58d0dd27ae13e2da84006e125f822349ffa8619eae6f646ddd8301ea2941c7a/share/hlint.yaml:1225:0
INPUT: issue1218 = uncurry (zipWith g) $ (a, b)
Refactor output is expected to contain: zipWith g a b
Actual: issue1218 = (zipWith g) a b
```

Namely that given `uncurry (zipWIth g) $ (a,b)` HLint generates the output `(zipWith g) a b`. But HLint knows that outer bracket is not useful, so strips it. The refactoring code doesn't know it's not useful, so leaves it present, and that gives us a warning.

@zliu41 as the refactor expert here. Should the test be more tolerant? Are we getting the output too early? Or is this just a test to mark `-- @NoRefactoring` and live with it?

**Comment by zliu41** [comment]
When HLint strips the brackets, it should be able to make the corresponding change to `ideaRefactoring`. I can look into how to do that. Meanwhile, to unblock this PR we can just `-- @NoRefactoring` for now.

**Comment by ndmitchell** [comment]
Try rebasing this on master, and hopefully the issue will have disappeared.

**Comment by Javran** [comment]
Thanks for the update! I've just rebased onto master and reverted changes to the changelog.

**Comment by ndmitchell** [comment]
Thanks!

**Pull request merged**
