### PR TITLE
Upgrade ghc-lib-parser-ex

### PR DESCRIPTION
**Pull request by shayne-fletcher**
## 8.10.0.4 released 2020-04-04
- Add expression predicates `isWholeFrac`, `isFieldPunUpdate`, `isStrictMatch`, `isMultiIf`, `isProc`, `isTransStmt`;
- Add pattern predicate `isPFieldPun`.

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
Tests all good locally (refactoring tests skipped). Appveyor failure unrelated I believe.

Screen Shot 2020-04-04 at 9 40 58 PM

**Comment by shayne-fletcher** [comment]
Ran again locally with refactor tests. Unable to reproduce (macOS).

Screen Shot 2020-04-04 at 9 51 58 PM

**Comment by ndmitchell** [comment]
We know not having this breaks, so let's merge!

**Comment by shayne-fletcher** [comment]
I concur that's the right thing to do. I'm also very confident the exhibited issue is unrelated to this. In any case, I'll put a hold on any further work on this front until we get the release out the door!

**Comment by ndmitchell** [comment]
I think now when we don't have any releases out the door is exactly the time to do it! Had we had a release out the door we'd have broken end users. Breaking the odd developer for a small amount of time isn't nearly as bad.

**Pull request merged**
