### PR TITLE
Require apply-refact 0.8.1.0

### LINKED ISSUE #389: Incorrect refactoring with list ranges using a step - [1,2..3] -> [12..3]
```
$ hlint --version
HLint v2.0.9, (C) Neil Mitchell 2006-2017
$ cat > Foo.hs
module Foo where
bar = ([1,2..3])
$ hlint Foo.hs 
Foo.hs:2:7: Warning: Redundant bracket
Found:
  ([1, 2 .. 3])
Why not:
  [1, 2 .. 3]

1 hint
$ hlint --refactor Foo.hs 
module Foo where
bar = [12..3]
$
```

The refactoring applied by `--refactor` is different (and incorrect) from the refactoring shown by `hlint` without any parameter for list ranges using steps.

### LINKED ISSUE #465: Refactor can't deal with UnicodeSyntax
From https://github.com/ndmitchell/hlint/issues/223#issuecomment-375145897:

hm, it doesn't seem to work when I enable the `-XUnicodeSyntax` extension.
my example file:
```haskell
module Model.File where

import qualified Data.Bson as Bson
import Data.Int (Int64)
import Data.Time.Clock (UTCTime)
import GHC.Generics (Generic)

-- | Represents a file stored in Mongo GridFS.
data File = File
  { _id        ∷ Bson.ObjectId
  , length     ∷ Int64
  , uploadDate ∷ UTCTime
  , fileName   ∷ String
  } deriving (Eq, Show, Generic)
```

```bash
 ▲ haskell/2018/spreadsheet-api cat .hlint.yaml
- arguments: [-XUnicodeSyntax]

 ▲ haskell/2018/spreadsheet-api hlint src/Model/File.hs --refactor
refactor: (RealSrcSpan SrcSpanOneLine "src/Model/File.hs" 10 16 17,"parse error on input \8216\8759\8217")
CallStack (from HasCallStack):
  error, called at src/Main.hs:189:22 in main:Main

 △ haskell/2018/spreadsheet-api hlint --version
HLint v2.0.11, (C) Neil Mitchell 2006-2017
```

Reported by @vyorkin

@ndmitchell says: Seems like the .yaml file is a red herring - my guess is refactor can't deal with unicode, perhaps because I should be passing more flags to it.

### LINKED ISSUE #499: found some incorrect refactors
While refactoring a large codebase, I found a list of bad refactors.
```
- mr13 = clamp' (-1, 1) $ -2.0*(q1*q3 - q0*q2)
+ mr13 = clamp' (-1, 1) 2.0*(q1*q3 - q0*q2)
```
```
- let newNames = map (("test_" ++ ) . show) $ [1,2..numTests] :: [String]
+ let newNames = map (("test_" ++ ) . show) [12..numTests] :: [String]
```
```
-        | newElevation' < -0.5*pi = -0.5*pi
+        | newElevation' < 0.5*pi = -0.5*pi
```

### LINKED ISSUE #528: Wrong refactoring for application without space
Given
```
f x = g(x)
```
`hlint --refactor` tells you
```
f x = gx  -- no space between g and x
```

### PR DESCRIPTION
**Pull request by zliu41**
Fixes #389, fixes #465, fixes #499, fixes #528.

### CODE REVIEW

**Comment by zliu41** [comment]
I have no idea how to make the CI use apply-refact 0.8.1.0. Neither one currently does.

**Comment by ndmitchell** [comment]
Thanks!

**Comment by ndmitchell** [comment]
I think we only install apply-refact on Appveyor. It uses whatever version is implied by the stack.yaml - I've just given a shot at bumping that.

**Comment by ndmitchell** [comment]
This now works on Appveyor.

**Comment by zliu41** [comment]
Thanks for updating CI!

**Pull request merged**
