### PR TITLE
Bump ghc-lib-parser-ex version

### PR DESCRIPTION
**Pull request by hseg**
Forgotten in b34a949
Closes: #1355

### CODE REVIEW

**Comment by hseg** [comment]
the build failures seem to be unrelated:
`neil: The .ghci file does not enough of -W -fwarn-unused-binds -fwarn-unused-imports -fwarn-orphans`

**Comment by hseg** [comment]
Hrm. Unsure of why this had this effect, but perhaps 4f02b44 isn't properly triggering the ``"-W" `elem` src`` branch of `checkGhci` in https://github.com/ndmitchell/neil?

**Comment by hseg** [comment]
Presuming #1357 works, have rebased this PR on top of it to prove it fixes the build

**Comment by ndmitchell** [comment]
The only change in this diff seems to be to .ghci? Or did merging things underneath it make this unnecessary?

**Comment by hseg** [comment]
Hrm, odd, should've checked again after rebasing. #1358 appears to have saved the original content, so it should be fine to just close this one.

**Pull request closed without merging**
