### PR TITLE
New module Extension

### PR DESCRIPTION
**Pull request by shayne-fletcher**
I was giving Extensions the same treatment that Fixities got.

### CODE REVIEW

**Comment by ndmitchell** [comment]
That seems like a good idea. Most of the pieces currently on HSE are extensions.

**Comment by shayne-fletcher** [comment]
I think the new module with the weeder yaml update should be ok. There failures are relating to hlint checks in unrelated code probably what you are working on. I'll leave it to you to decide what to do with this  and back off for the moment - let me know if you have a job for me!

**Comment by ndmitchell** [comment]
Why not wire this in, deleting the existing copies, which should remove the weeder issues?

Yep, there are a few latent hlint errors from my last refactor. Fixing them shortly.

**Comment by shayne-fletcher** [comment]
> Why not wire this in, deleting the existing copies, which should remove the weeder issues?

I already did but commit conflicts that emerged in the period I did the job  broke my work 😄 . OK, I'll do that.

**Comment by ndmitchell** [comment]
Sorry! I'm hands off for the next few hours (apart from potentially to fix the hlint issues I introduced)

**Comment by shayne-fletcher** [comment]
Done. Rebasing after your hlint fixes should see this green in CI.

**Comment by ndmitchell** [comment]
OK, I'll trust you and merge it now!

**Comment by ndmitchell** [comment]
Looking at imports of Language.Haskell.Exts, I see Hint.Extensions, Hint.Pragmas and CmdLine all use the extension stuff of HSE, so that seems a good one to reduce.

**Pull request merged**
