### PR TITLE
Propagate exit code from child process.

### PR DESCRIPTION
**Pull request by mpickering**
The previous change broke all my tooling integration!

### CODE REVIEW

**Comment by ndmitchell** [comment]
Could we have runRefactoring return an ExitCode, then runHints actually exitWith? Having all the exit stuff in runHints means I have a chance of finding it in the future when I wonder "hmm, why is that not getting to the next line". Other than that, looks good.

**Comment by mpickering** [comment]
Yep no problem.

**Comment by ndmitchell** [comment]
Sorry, I hadn't spotted you had updated the branch! All merged now.

**Comment by mpickering** [comment]
I have written some bindings for emacs, vim and atom. Do you think I should put a link in the README?

https://github.com/mpickering/hlint-refactor-mode
https://github.com/mpickering/hlint-refactor-atom
https://github.com/mpickering/hlint-refactor-vim

**Comment by ndmitchell** [comment]
Yes, sounds great.

**Pull request merged**
