### PR TITLE
Avoid using head with a sloppy default

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by josephcsible** [comment]
Looks like the build is failing because HLint itself triggers this rule. The code where it does so is the same part of the code I'm touching in #834, so I'll wait until it's merged to fix this one to avoid an unnecessary merge conflict.

**Comment by ndmitchell** [comment]
`fromMaybe x (listToMaybe y)` is quite a lot longer and (to me) less intuitive than `head (x ++ [y])`. If you use safe you can use `headDef` which is cleaner, but without it, I don't see a nicer pattern.

**Comment by josephcsible** [comment]
I thought up an alternative. Do you like this replacement better?

**Comment by ndmitchell** [comment]
Not really - that seems a lot more confusing than the Maybe variant.

**Comment by josephcsible** [comment]
I'll table this for now unless/until there's something better then.

**Pull request closed without merging**
