### PR TITLE
Add a rule to use `find`

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Great idea! Just needs a quick fix then i'll merge

**Comment by josephcsible** [comment]
Do you mean something you'll fix yourself, or something you want me to fix in it? If the latter, what is it?

**Comment by ndmitchell** [comment]
I wrote the comments, but as part of a review that I forgot to submit, so you couldn't see it. I've pushed the fixes myself - you need to write `x` if you want it to be a wildcard, since `xs` is more than one letter, so matches only the literal `xs`.

**Comment by ndmitchell** [comment]
And thanks for the patch!

**Pull request merged**
