### PR TITLE
HSE.All -> All

### PR DESCRIPTION
**Pull request by shayne-fletcher**
A last(?) vestige removed? Move `src/HSE/All.hs` to `src/All.hs`.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Not a fan of moving this to All. Before we had Hint.All and HSE.All (which was really just all the AST stuff). Probably should be GHC.All? Or maybe GHC.Parser?

**Comment by shayne-fletcher** [comment]
> Not a fan of moving this to All. Before we had Hint.All and HSE.All (which was really just all the AST stuff). Probably should be GHC.All? Or maybe GHC.Parser?

I'm easy @ndmitchell. I'll ask you to make the call and I'll make it happen!

**Comment by ndmitchell** [comment]
Does GHC.Parser seem right to you?

**Comment by shayne-fletcher** [comment]
> Does GHC.Parser seem right to you?

To me that choice sparks dissonance with the actual `GHC.Parser` module. Looking at the contents of `All`, I'd be inclined to advocate `Driver` actually.

**Comment by shayne-fletcher** [comment]
> > Does GHC.Parser seem right to you?
> 
> To me that choice sparks dissonance with the actual `GHC.Parser` module. Looking at the contents of `All`, I'd be inclined to advocate `Driver` actually (but even then if that were `GHC.Driver` we have overloading with GHC actual hence I literally mean `Driver`).

Hmmm. Maybe therein is the path out? Recognizing that we've been in states where there are parallel parse trees, perhaps `Driver.GHC`?

**Comment by shayne-fletcher** [comment]
In any case, if between the suggestions of `GHC.Parser` and `GHC.All`, I would vote for `GHC.All`.

**Comment by ndmitchell** [comment]
It seems either it should go somewhere in the GHC.* tree. Or, alternatively, we need a new AST.* tree and things should remain in GHC.* if they are GHC utility wrappers, and move to AST.* if (some condition I can't articulate)

**Comment by shayne-fletcher** [comment]
> It seems either it should go somewhere in the GHC.* tree. Or, alternatively, we need a new AST.* tree and things should remain in GHC.* if they are GHC utility wrappers, and move to AST.* if (some condition I can't articulate)

😁 

I say, let's go with `GHC.All`. It's a mapping of the status quo. When/if the need proves itself to do more, we can cross those bridges as the need arises.

**Comment by ndmitchell** [comment]
Makes sense!

**Comment by shayne-fletcher** [comment]
> if they are GHC utility wrappers, and move to AST.* i

I think there is very little code now that matches the tag "GHC utility". Really what resides under `GHC` are those core algorithms like bracket, unify, pretty lambda etc. that are now expressed in terms of GHC. If we were to find a better name for those I think we could eliminate `GHC.Util` entirely. Something to think about going forward.

**Comment by shayne-fletcher** [comment]
> Makes sense!

I'll get on it and update this PR accordingly. Stand by.

**Comment by ndmitchell** [comment]
Makes a lot of sense - thanks!

**Pull request merged**
