### PR TITLE
Enable refactoring for "Use lambda"

### PR DESCRIPTION
**Pull request by zliu41**

### CODE REVIEW

**Comment by zliu41** [comment]
CI appears to be down

**Comment by ndmitchell** [comment]
The Travis seems to be failing legitimately, with:

```
src/Hint/Lambda.hs:1:1-74: Warning: Avoid restricted extensions
Found:
  {-# LANGUAGE LambdaCase, PatternGuards, TypeApplications, ViewPatterns #-}
```

Is the type application there actually useful? I'm surprised none of the existing subexpressions constrain the type already.

**Comment by zliu41** [comment]
Oops, don't know how I missed that. I changed type application to type annotation.

`noLoc :: HasSrcSpan a => SrcSpanLess a -> a` where `SrcSpanLess` is a non-injective type family, so GHC needs to be told what `a` is.

I also re-generated the summary, which seems to have some unrelated changes.

**Comment by ndmitchell** [comment]
Thanks! We need to build up some CI tooling around generating the summary, but I don't quite no what yet, and its likely we'll have to move CI entirely, so no point doing it now.

**Pull request merged**
