### PR TITLE
Add some hints to use sequenceA_ and traverse_

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the contribution. I find these a bit harder to read, and prefer the more specific version. However, I appreciate that neither choice is universally held. How about moving these to the generalise section of hints in the .yaml file, then people can opt in if they want.

**Comment by josephcsible** [comment]
I think generalize-for-conciseness is a better fit for these than generalize. Do you agree?

**Comment by ndmitchell** [comment]
Agreed, that does seem the right place - thanks.

**Comment by ndmitchell** [comment]
Thanks, yep, I agree!

**Pull request merged**
