### PR TITLE
Operator wildcards

### PR DESCRIPTION
**Pull request by yairchu**
Fix https://github.com/ndmitchell/hlint/issues/623

### CODE REVIEW

**Comment by ndmitchell** [comment]
Looks good. Can I get:

* A comment that says that subst on ??? style variables is guaranteed to be a Var
* A test. I think `data/Test.hs` might be a reasonable place to put it?

**Comment by yairchu** [comment]
Added a test.

As `toNamed` is invoked in 6 places here, where would you place the comment?

**Comment by ndmitchell** [comment]
I'd put the comment on the type Subst itself

**Comment by yairchu** [comment]
Changed the code because CI noted that `hlint` proposes improvements, and in that I also added the comment in an extracted function that now does the `toNamed . fromNamed`.

**Comment by ndmitchell** [comment]
Thanks, all merged! Would a release help you?

**Comment by yairchu** [comment]
There's no rush, I'm just using the modified version :)

Do you think that it would be a good idea now to replace the operator sections code in `niceLambdaR` with more succinct rules in `hlint.yaml`?

**Comment by ndmitchell** [comment]
The `niceLambdaR` stuff gets used in a few places, as a helper in other rules, so I don't think replacing it would work.

**Comment by ndmitchell** [comment]
FWIW I released a new version anyway

**Pull request merged**
