### PR TITLE
Update ghc-lib-parser-ex; remove GHC.Util.RdrName

### PR DESCRIPTION
**Pull request by shayne-fletcher**
## 8.10.0.8 released 2020-05-14
- New module `Language.Haskell.GhclibParserEx.GHC.Types.Name.Reader`

### CODE REVIEW

**Comment by ndmitchell** [comment]
Does rdr stand for Reader? If not, the module is a bit weirdly named.

**Comment by shayne-fletcher** [comment]
In the GHC API, the module `RdrName` has moved to `GHC.Types.Name.Reader` and has the representative function `rdrNameOcc` for example. The convention in `ghc-lib-parser-ex` is to align modules with their companion GHC API modules. I'm a bit unsure about what you're asking but hopefully I've answered anyway? 😃

**Comment by shayne-fletcher** [comment]
AppVeyor build failure looks toolchain related and transient. Hit the rebuild please?

**Comment by shayne-fletcher** [comment]
Oh wow! Check it out! This is the 1000th PR on this repo! 🎉

**Comment by ndmitchell** [comment]
If GHC is doing it, that's good enough for me! The Appveyor is crap because GHC keeps segfaulting on Windows - I've started just ignoring it.

**Pull request merged**
