### PR TITLE
Update GitHub Actions badge on readme

### PR DESCRIPTION
**Pull request by cherryblossom000**
https://github.com/badges/shields/issues/8671

### CODE REVIEW

**Review by zliu41 — APPROVED** [review]

**Comment by zliu41** [comment]
Thanks!

**Comment by shayne-fletcher** [comment]
@zliu41 @ndmitchell this commit appears to have broken CI

**Comment by zliu41** [comment]
Yeah. This commit is fine; https://github.com/ndmitchell/neil needs an update.

**Comment by shayne-fletcher** [comment]
> Yeah. This commit is fine; https://github.com/ndmitchell/neil needs an update.

https://github.com/ndmitchell/neil/pull/58

**Comment by ndmitchell** [comment]
Merged that, so hopefully will work now

**Pull request merged**
