### PR TITLE
add more rules to the lens group

### PR DESCRIPTION
**Pull request by yairchu**
(these rules are for stuff that I had stumbled with in my own code and I believe they could help others)

### CODE REVIEW

**Comment by ndmitchell** [comment]
Not a fan of the zipWith ones since they're changing from the base library to the lens library. I personally prefer zipFrom to that pattern. The rest look good though, assuming they are correct (I don't know enough about lens to be sure - so please double check them yourself)

**Comment by yairchu** [comment]
I I guess those would better fit a `lens-zealots` group :) Which could have more rules, like:

    - hint: {lhs: "Data.Set.member a", rhs: "(^. Control.Lens.contains a)"}

**Comment by ndmitchell** [comment]
A lens zealots group off by default is fine by me.

**Comment by yairchu** [comment]
I was half kidding with the `lens-zealots` group :)

**Comment by ndmitchell** [comment]
Thanks, looks good!

**Pull request merged**
