### PR TITLE
Documents how to extend HLint by adding inline tests, resolved #260

### LINKED ISSUE #260: Document how to develop with tests
@tomjaguarpaw in #257 had no idea where to put the tests, or how to run them. A sad consequence of it not being guessable in any way. I should document it in the README.

### PR DESCRIPTION
**Pull request by daniel-j-h**
First try at some docs for how inline tests work. The behavior I wrote down here is what I figured out by poking HLint and some inline tests but more importantly reading `Annotations.hs`.

### CODE REVIEW

**Comment by lwm** [comment]
Oh, I think we're missing a link to the TOC at the top?

**Comment by ndmitchell** [comment]
-- is for comments, but very few tests use it, so no need to even mention it. <COMMENT> is the escaped version of a comment, so the test is literally working on comments. It's exceptionally rare so can be ignored for the docs.

Other than that, looks good

**Comment by daniel-j-h** [comment]
Added TOC. @ndmitchell I think Github swallowed your second sequence of chars: care to elaborate? Okay with the `zipFrom` example?

**Comment by ndmitchell** [comment]
-- is for comments, but very few tests use it, so no need to even mention it. [COMMENT] is the escaped version of a comment, so the test is literally working on comments. It's exceptionally rare so can be ignored for the docs.

Where I've used square brackets instead of angles. ZipFrom is fine as an example.

**Comment by ndmitchell** [comment]
Thanks for the docs. Sorry it took so long to merge - just drifted off my radar a bit too much.

**Pull request merged**
