### PR TITLE
Fix no warn on (x.y) by treating x.y as atom

### PR DESCRIPTION
**Pull request by benbellick**
This is to resolve issue #1471

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
the fix looks good but the test doesn't show it. `OverloadedRecordDot` is not default enabled so in `issue1471 = (x.y)`, `(x.y)` is parsed to a parenthesized function composition and will generate a redundant brackets hint both before your fix and after it.

i suggest these tests from #1471:
```haskell
-- no record dot syntax
referenceDesignator = ReferenceDesignator (p.placementReferenceDesignator)

-- record dot syntax
{-# LANGUAGE OverloadedRecordDot #-} \
referenceDesignator = ReferenceDesignator (p.placementReferenceDesignator) -- p.placementReferenceDesignator
``` 
as reported in the ticket, for the second test, before your fix it won't generate a redundant bracket hint but after your fix it will!

**Comment by benbellick** [comment]
Hey Shayne, thanks for the comments! I have updated the tests. Just to be clear, in the first case (w/o record dot syntax), the expression `p.placementReferenceDesignator` is parsed as `p . placementReferenceDesignator`, i.e. as two functions combined with the composition operator `.`. Is that correct?

**Review by shayne-fletcher — APPROVED** [review]
looks good!

**Comment by shayne-fletcher** [comment]
>  Just to be clear, in the first case (w/o record dot syntax), the expression `p.placementReferenceDesignator` is parsed as `p . placementReferenceDesignator`, i.e. as two functions combined with the composition operator `.`. Is that correct? 

yes. if `OverloadedRecordDot` is not in effect the `.` in the expression above is parsed as an `ITdot` token which denotes function composition.

**Comment by benbellick** [comment]
It seems that OverloadedRecordDot was added in version [9.2](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_record_dot.html), so version 9.0 is perhaps causing a test failure. Any suggestion on how to deal with this? Perhaps a way to ignore certain tests based off of version?

**Comment by shayne-fletcher** [comment]
@benbellick if the second test were updated to
```haskell
-- record dot syntax
{-# LANGUAGE OverloadedRecordDot #-} \
referenceDesignator = ReferenceDesignator (p.placementReferenceDesignator) -- @Warning p.placementReferenceDesignator @NoRefactor: refactor requires GHC >= 9.2.1
```
i think it will pass the currently failing 9.0 test.

**Comment by benbellick** [comment]
@shayne-fletcher Thanks for the help. I have updated the test!

**Comment by shayne-fletcher** [comment]
Thanks for contributing to hlint!

**Comment by benbellick** [comment]
My pleasure! I love Haskell and hope to keep contributing to the community however I can. Thanks for the help!

**Pull request merged**
