### PR TITLE
Prune modules, reduce qualification

### PR DESCRIPTION
**Pull request by shayne-fletcher**
Indulge in some cleaning up : remove `GHC.Util.Outputable`, remove indirections to parse functions and drop `GHC.` qualifications in many modules where now we can.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Awesome. I'll wait for CI to agree and give it a merge. I note there's plenty of `'`s to clean up too :)

**Comment by shayne-fletcher** [comment]
> I note there's plenty of 's to clean up too :)

Yep. Plenty to keep us busy 😄

**Comment by ndmitchell** [comment]
Sweet - I just enabled/disabled Travis harder, and it seems to have sprung back to life!

**Comment by shayne-fletcher** [comment]
> Sweet - I just enabled/disabled Travis harder, and it seems to have sprung back to life!

Thank goodness.

**Comment by ndmitchell** [comment]
Thanks!

**Pull request merged**
