### PR TITLE
Suggest replacing 'data' with 'newtype' when possible

### PR DESCRIPTION
**Pull request by niteria**
This implements the idea from #279.

### CODE REVIEW

**Comment by ndmitchell** [comment]
This looks good. I'll take a proper look shortly.

**Comment by ndmitchell** [comment]
Thanks! All merged. I changed it from warning to suggestion, and gave a note warning the user that it changes strictness properties, but minor tweaks - nice test cases and a good catch on existentials.

**Comment by niteria** [comment]
Thanks!
To give credit where it's due, this is @DiegoNolan's patch, I'm only upstreaming it.

**Comment by ndmitchell** [comment]
Thanks to both of you!

**Pull request merged**
